Repository oluyaratosin123/Recipe-App-II, pull requests merged in 2022-06, with the labels that each got.

#1 --
  README.md
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement

#26 Recipe app - add recipe model, specs and validation
  app/models/recipe.rb
  db/migrate/20220620191715_create_recipes.rb
  db/schema.rb
  spec/factories/recipes.rb
  spec/models/recipe_spec.rb
Labels: documentation

#28 Recipe app - create recipe controller and all view features
  app/controllers/recipes_controller.rb
  app/helpers/recipes_helper.rb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/public_recipes.html.erb
  app/views/recipes/show.html.erb
  app/views/shared/_flash.html.erb
  config/routes.rb
  spec/helpers/recipes_helper_spec.rb
  spec/requests/recipes_spec.rb
Labels: documentation

#35 Recipe app - Feature/user model
  Gemfile.lock
  app/models/user.rb
  db/migrate/20220621191650_create_users.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: documentation

#38 Recipe app - Feature/Create Foods Controller - Student A #6
  app/controllers/foods_controller.rb
  app/helpers/foods_helper.rb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/foods/show.html.erb
  app/views/shared/_form.html.erb
  spec/helpers/foods_helper_spec.rb
  spec/requests/foods_spec.rb
Labels: documentation

#39 Recipe app - Feature/recipe helper
  README.md
  app/helpers/recipes_helper.rb
  app/models/ability.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/schema.rb
Labels: documentation

#41 Recipe app - Feature/add authentication
  app/controllers/application_controller.rb
  app/helpers/recipes_helper.rb
  app/models/food.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  config/database.yml
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20220516140223_create_recipes.rb
  db/migrate/20220516140721_create_users.rb
  db/migrate/20220516173040_create_foods.rb
  db/migrate/20220517090735_create_recipe_foods.rb
  db/migrate/20220621191650_create_users.rb
  db/migrate/20220622081749_create_foods.rb
  db/migrate/20220623161330_add_user_ref_to_recipes.rb
  db/migrate/20220623165029_add_devise_to_users.rb
  db/schema.rb
Labels: group

#42 Recipe app - Feature/add authorization
  app/controllers/foods_controller.rb
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/helpers/recipes_helper.rb
  app/models/ability.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/routes.rb
Labels: group

#43 Recipe app - Feature/shopping list
  app/controllers/shopping_lists_controller.rb
  app/helpers/shopping_lists_helper.rb
  app/views/shopping_lists/index.html.erb
  config/routes.rb
  spec/helpers/shopping_lists_helper_spec.rb
  spec/requests/shopping_lists_spec.rb
Labels: documentation
